[project]
name = "twitchchatscraper"
version = "0.2"
dependencies = [
    "playwright",
    "pydantic",
    "click",
    "streamerdb",
    "PyYAML",
]
requires-python = ">= 3.10"

[project.scripts]
twitchchatscraper = "twitchchatscraper:cli"
